modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${license}"
logoBlur=false
issueTrackerURL="${issue_tracker}"
logoFile="${mod_id}_icon.png"

[[mods]]
    modId="${mod_id}"
    version="${forge_mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/wendall911/ReadyPlayerFun/${mod_update_branch}/files/updates.json"
    authors="${mod_author}"
    credits="${mod_credits}"
    description='''
    ${mod_description}
    '''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="AFTER"
    side="SERVER"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${forge_mc_version_range}"
    ordering="NONE"
    side="SERVER"
