modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${license}"
logoBlur=false
issueTrackerURL="${issue_tracker}"
logoFile="${mod_id}_icon.png"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    updateJSONURL="${mod_update_url}"
    authors="${mod_author}"
    credits="${mod_credits}"
    description='''
    ${mod_description}
    '''
[[dependencies.readyplayerfun]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="AFTER"
    side="SERVER"
[[dependencies.readyplayerfun]]
    modId="minecraft"
    mandatory=true
    versionRange="${forge_mc_version_range}"
    ordering="NONE"
    side="SERVER"
