plugins {
    id 'idea'
    id 'maven-publish'
    id 'fabric-loom'
    id 'me.modmuss50.mod-publish-plugin'
    id 'io.freefair.lombok'
}

version = "${minecraft_version}-${mod_version}-FABRIC"
archivesBaseName = "${mod_id}"

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings(loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${minecraft_version}:${mappings_version}@zip")
    })
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation project(":Common")

    modImplementation group: 'technology.roughness.whitenoise', name: 'whitenoise-fabric', version: "${whitenoise_range}"
    include group: 'technology.roughness.whitenoise', name: 'whitenoise-fabric', version: "${whitenoise_version}"

    modLocalRuntime("com.terraformersmc:modmenu:${mod_menu_version}") {
        transitive = false
    }
}

loom {
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

def resourceTargets = ['fabric.mod.json', 'pack.mcmeta', '*.mixins.json']
def replaceProperties = [
    'version': version, 'fabric_mc_version_range': fabric_mc_version_range, 'license': license,
    'mod_id': mod_id, 'mod_author': mod_author, 'mod_description': mod_description,
    'mod_name': mod_name, 'issue_tracker': issue_tracker, 'fabric_loader_min_version': fabric_loader_min_version
]

processResources {
    from project(":Common").sourceSets.main.resources
    duplicatesStrategy(DuplicatesStrategy.FAIL)
    inputs.properties replaceProperties
    replaceProperties.put 'project', project
    exclude '.cache'

    filesMatching(resourceTargets) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile) {
    source(project(":Common").sourceSets.main.allSource)
}

def changelogFile = project(":").projectDir.toString() + '/build/libs/changelog.txt'
def publishFile = project(":").projectDir.toString() + "/Fabric/build/libs/${archivesBaseName}-${version}.jar"

publishMods {
    file = file(publishFile)
    if (file(changelogFile).exists()) {
        changelog = file(changelogFile).text
    }
    type = "${release_type}".startsWith("release") ? STABLE : ("${release_type}".startsWith("beta") ? BETA : ALPHA)
    modLoaders.addAll(['fabric'])
    dryRun = providers.environmentVariable('DO_RELEASE').getOrNull() == null

    if (project.hasProperty('rpfcurseApiKey')) {
        curseforge {
            accessToken = project.rpfcurseApiKey
            projectId = project.rpfcurseId
            javaVersions.add(JavaVersion.toVersion("${java_version}"))
            clientRequired = false
            serverRequired = true
            minecraftVersions.addAll("${release_versions}".split(','))
            requires('fabric-api')
            optional('betterdays')
            optional('serene-seasons')
        }
    }
    if (project.hasProperty('rpfModrinthId')) {
        modrinth {
            accessToken = project.modrinthKey
            projectId = project.rpfModrinthId
            minecraftVersions.addAll("${release_versions}".split(','))
            requires('fabric-api')
            optional('betterdays')
            optional('serene-seasons')
        }
    }
}
