plugins {
    // see https://fabricmc.net/develop/ for new versions
    // see https://maven.fabricmc.net/fabric-loom/fabric-loom.gradle.plugin/ for latest
    id 'net.fabricmc.fabric-loom' version '1.15.5' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.141' apply false
    // https://plugins.gradle.org/plugin/se.bjurr.gitchangelog.git-changelog-gradle-plugin
    id 'se.bjurr.gitchangelog.git-changelog-gradle-plugin' version '3.1.2' apply(false)
    // https://plugins.gradle.org/plugin/me.modmuss50.mod-publish-plugin
    id 'me.modmuss50.mod-publish-plugin' version '1.1.0' apply(false)
    id 'io.freefair.lombok' version '8.14.2' apply false
}
