# Gradle
org.gradle.jvmargs=-Xmx3G

# Version
version=3.0.0.1
last_mod_version=3.0.0.0

# Common
minecraft_version=1.18.2
minecraft_short_version=1.18
java_version=17
mixin_version=0.8.5

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2022.11.06

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=40.3.11
forge_version_range=[40,)
forge_mc_version_range=[1.18.2,1.18.3)

# Mod options
mod_id=readyplayerfun
mod_name=ReadyPlayerFun
mod_author=wendall911
mod_credits=ashar42
license=MIT
issue_tracker=https://github.com/wendall911/ReadyPlayerFun/issues
mod_description=Pause time and seasons when no players are logged in.
mod_update_branch=1.18.2

# CurseForge/Modrinth Options
release_type=release
release_versions=1.18.2
