# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=3.1.0.2
last_mod_version=3.1.0.1
group=com.github.wendall911.readyplayerfun

# Common
minecraft_version=26.1.2
mixin_extras_version=0.5.3
whitenoise_version=2.2.0
whitenoise_range=[2.2.0,3.0.0)
fabric_whitenoise_range=[">=2.2.0","<=3.0.0"]
mixin_version=0.8.5
java_version=25

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.27-beta
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[26.1, 26.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.146.1+26.1.2
fabric_api_min_version=>=0.143.10
fabric_loader_version=0.19.2
fabric_loader_min_version=>=0.15
fabric_mc_version_range=[">26.1-"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=18.0.0-alpha.8

# Mod options
mod_display_name=Ready Player Fun
mod_id=readyplayerfun
mod_name=ReadyPlayerFun
mod_author=wendall911
mod_credits=ashar42
license=MIT
mod_description=Pause time and seasons when no players are logged in.
mod_update_branch=26.1

# CurseForge/Modrinth Options
curseforge_api_key_prop=rpfcurseApiKey
curseforge_id=322036
curseforge_slug=ready-player-fun
modrinth_api_key_prop=modrinthKey
modrinth_id=AwiAYDUq
discord_webhook_prop=rpfDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=26.1,26.1.1,26.1.2
