modLoader="javafml"
loaderVersion="${loader_version}"
license="MIT"

[[mods]]
  modId="readyplayerfun"
  displayName="Ready Player Fun"
  description="Pause time and seasons when no players are logged in."
  version="${version}"
  displayURL="https://github.com/wendall911/ReadyPlayerFun"
  updateJSONURL="https://raw.githubusercontent.com/wendall911/ReadyPlayerFun/1.19.x/files/updates.json"
  authors="wendall911"
  credits="ashar42"
  logoFile="logo.png"

[[dependencies.readyplayerfun]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="AFTER"
    side="SERVER"
[[dependencies.readyplayerfun]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="SERVER"
