plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle'
    id 'org.parchmentmc.librarian.forgegradle'
    id 'org.spongepowered.mixin'
    id 'se.bjurr.gitchangelog.git-changelog-gradle-plugin'
    id 'me.modmuss50.mod-publish-plugin'
    id 'io.freefair.lombok'
}

def actualVersion = version
version = "${minecraft_version}-${version}-FORGE"
archivesBaseName = "${mod_id}"

mixin {
    add sourceSets.main, "${mod_id}-refmap.json"

    config "${mod_id}.forge.mixins.json"
}

minecraft {
    mappings channel: 'parchment', version: "${mappings_version}-${minecraft_version}"

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Client'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            args "-mixin.config=${mod_id}.forge.mixins.json"
            mods {
                modClientRun {
                    source sourceSets.main
                    source project(":Common").sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Server'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            args "-mixin.config=${mod_id}.forge.mixins.json"
            mods {
                modServerRun {
                    source sourceSets.main
                    source project(":Common").sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
    compileOnly project(":Common")

    implementation fg.deobf(group: 'technology.roughness.whitenoise', name: "whitenoise-${minecraft_version}-forge", version: "${whitenoise_version}")
    jarJar fg.deobf(group: 'technology.roughness.whitenoise', name: "whitenoise-${minecraft_version}-forge", version: "${whitenoise_version}") {
        jarJar.pin(it, "${whitenoise_version}")
        jarJar.ranged(it, "${whitenoise_range}")
    }
}

// Throw errors on warnings. Can also disable warnings here.
compileJava {
    source(project(":Common").sourceSets.main.allSource)
    options.compilerArgs << "-Xlint:all,-classfile,-processing,-deprecation,-serial" << "-Werror"
}

tasks.withType(JavaCompile) {
    source(project(":Common").sourceSets.main.allSource)
}

def resourceTargets = ['META-INF/mods.toml', 'pack.mcmeta', '*.mixins.json']
def replaceProperties = [
    'version': actualVersion,
    'minecraft_version': minecraft_version,
    'forge_mc_version_range': forge_mc_version_range,
    'forge_version_range': forge_version_range,
    'license': license,
    'mod_id': mod_id,
    'mod_author': mod_author,
    'mod_description': mod_description,
    'mod_display_name': mod_display_name,
    'mod_name': mod_name,
    'mod_credits': mod_credits,
    'mod_update_branch': mod_update_branch,
    'pack_format': pack_format,
    'curseforge_slug': curseforge_slug
]

processResources {
    from project(":Common").sourceSets.main.resources
    duplicatesStrategy(DuplicatesStrategy.FAIL)
    inputs.properties replaceProperties
    replaceProperties.put 'project', project

    filesMatching(resourceTargets) {
        expand replaceProperties
    }
}

tasks.jarJar.finalizedBy('reobfJar')
jar.finalizedBy('reobfJarJar')

reobf {
    jarJar {}
}

tasks.jarJar.configure {
    archiveClassifier.set("")
}

jarJar {
    enable()
}

task changelog(type: se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask) {
    file.set(new File(project(":").projectDir.toString() + '/build/libs/changelog.txt'));
    templateContent.set(file(project(":").projectDir.toString() + '/files/templates/changelog.mustache').getText('UTF-8'));
    toRevision.set('HEAD');
    fromRevision.set("${minecraft_version}-${last_mod_version}");
}

def updates = tasks.register("generateUpdates", Copy) {
    it.outputs.upToDateWhen {
        false
    }

    it.from("../files/templates/") {
        include 'updates.json'
        expand replaceProperties
    }

    it.into '../files/'
}

tasks.generateUpdates.mustRunAfter('jar')

tasks.build.dependsOn('changelog', 'generateUpdates')

def changelogFile = project(":").projectDir.toString() + '/build/libs/changelog.txt'
def publishFile = project(":").projectDir.toString() + "/Forge/build/libs/${archivesBaseName}-${version}.jar"

publishMods {
    file = file(publishFile)
    if (file(changelogFile).exists()) {
        changelog = file(changelogFile).text
    }
    type = "${release_type}".startsWith("release") ? STABLE : ("${release_type}".startsWith("beta") ? BETA : ALPHA)
    modLoaders.addAll(['neoforge', 'forge'])
    dryRun = providers.environmentVariable('DO_RELEASE').getOrNull() == null

    if (project.hasProperty("${curseforge_api_key_prop}")) {
        curseforge {
            accessToken = project.property("${curseforge_api_key_prop}")
            projectId = "${curseforge_id}"
            projectSlug = "${curseforge_slug}"
            javaVersions.add(JavaVersion.toVersion("${java_version}"))
            clientRequired = false
            serverRequired = true
            minecraftVersions.addAll("${release_versions}".split(','))
            optional('catalogue')
            optional('actually-harvest')
            optional('betterdays')
            optional('charged-charms')
            optional('creeper-fireworks')
            optional('homeostatic')
            optional('magical-psi-revival')
            optional('simpletextoverlay')
            optional('survivalist-essentials')
            optional('tinkersurvival')
            optional('hourglass')
            optional('serene-seasons')
        }
    }
    if (project.hasProperty("${modrinth_api_key_prop}")) {
        modrinth {
            accessToken = project.property("${modrinth_api_key_prop}")
            projectId = "${modrinth_id}"
            minecraftVersions.addAll("${release_versions}".split(','))
            optional('actually-harvest')
            optional('betterdays')
            optional('charged-charms')
            optional('creeper-fireworks-mod')
            optional('homeostatic')
            optional('magical-psi-revival')
            optional('simpletextoverlay')
            optional('survivalist-essentials')
            optional('tinkersurvival')
            optional('hourglass')
            optional('serene-seasons')
        }
    }
    if (project.hasProperty("${discord_webhook_prop}")) {
        discord {
            webhookUrl = project.property("${discord_webhook_prop}")
            dryRunWebhookUrl = project.property("${discord_dryrun_webhook_prop}")
            username = "${mod_author}"
            content = changelog.map {
                "# A new version of ${mod_display_name} for Forge ${minecraft_version} has been released! \n" + it
            }
        }
    }
}
