plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

archivesBaseName = "${mod_id}-common"

neoForge {
    neoFormVersion = neo_form_version
    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = mappings_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: "${mixin_version}"
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: "${mixin_extras_version}"
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: "${mixin_extras_version}"
    implementation group: 'technology.roughness.whitenoise', name: 'whitenoise-common', version: "${whitenoise_version}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.files
}
