plugins {
    id 'java'
    id 'org.spongepowered.gradle.vanilla'
    id 'io.freefair.lombok'
}

archivesBaseName = "${mod_id}-common"

minecraft {
    version(minecraft_version)
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: "${mixin_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation group: 'technology.roughness.whitenoise', name: 'whitenoise-common', version: "${whitenoise_version}"
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

processResources {
    filesMatching("pack.mcmeta") {
        expand 'mod_name': project.mod_name
    }
}
