plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'io.github.goooler.shadow'
}

def modLoader = "${project.name}".toUpperCase()
def actualVersion = version
version = "${version}-${modLoader}"

neoForge {
    version = neoforge_version
    parchment {
        minecraftVersion = mappings_minecraft_version
        mappingsVersion = mappings_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation group: 'technology.roughness.whitenoise', name: "whitenoise-${minecraft_version}-neoforge", version: "${whitenoise_version}"
    jarJar group: 'technology.roughness.whitenoise', name: "whitenoise-${minecraft_version}-neoforge", version: "${whitenoise_version}"
}

shadowJar {
    archiveClassifier = ''
}

def changelogFile = project(":").projectDir.toString() + '/build/libs/changelog.txt'
def publishFile = project(":").projectDir.toString() + "/NeoForge/build/libs/${archivesBaseName}-${version}.jar"
def display_name = "${project.name} ${minecraft_version}-${version}"
def display_version = "${minecraft_version}-${version}"

publishMods {
    file = file(publishFile)
    if (file(changelogFile).exists()) {
        changelog = file(changelogFile).text
    }
    displayName = "${display_name}"
    version = "${display_version}"
    type = "${release_type}".startsWith("release") ? STABLE : ("${release_type}".startsWith("beta") ? BETA : ALPHA)
    modLoaders.add('neoforge')
    dryRun = providers.environmentVariable('DO_RELEASE').getOrNull() == null

    if (project.hasProperty("${curseforge_api_key_prop}")) {
        curseforge {
            accessToken = project.property("${curseforge_api_key_prop}")
            projectId = "${curseforge_id}"
            projectSlug = "${curseforge_slug}"
            javaVersions.add(JavaVersion.toVersion("${java_version}"))
            clientRequired = false
            serverRequired = true
            minecraftVersions.addAll("${release_versions}".split(','))
            optional('actually-harvest')
            optional('betterdays')
            optional('charged-charms')
            optional('creeper-fireworks')
            optional('homeostatic')
            optional('magical-psi-revival')
            optional('simpletextoverlay')
            optional('survivalist-essentials')
            optional('tinkersurvival')
            optional('catalogue')
            optional('hourglass')
            optional('serene-seasons')
        }
    }
    if (project.hasProperty("${modrinth_api_key_prop}")) {
        modrinth {
            accessToken = project.property("${modrinth_api_key_prop}")
            projectId = "${modrinth_id}"
            minecraftVersions.addAll("${release_versions}".split(','))
            optional('actually-harvest')
            optional('betterdays')
            optional('charged-charms')
            optional('creeper-fireworks-mod')
            optional('homeostatic')
            optional('magical-psi-revival')
            optional('simpletextoverlay')
            optional('survivalist-essentials')
            optional('tinkersurvival')
            optional('hourglass')
            optional('serene-seasons')
        }
    }
    if (project.hasProperty("${discord_webhook_prop}")) {
        discord {
            webhookUrl = project.property("${discord_webhook_prop}")
            dryRunWebhookUrl = project.property("${discord_dryrun_webhook_prop}")
            username = "${mod_author}"
            content = changelog.map {
                "# A new version of ${mod_display_name} for NeoForge ${minecraft_version} has been released! \n" + it
            }
        }
    }
}
