#!/bin/bash
# Ugly but effective
git_tag=$(git name-rev --name-only --tags HEAD 2>/dev/null | sed 's/^undefined$//')
if [[ -n "$git_tag" && -z "$(git status --porcelain)" ]]; then
    echo "Releasing: $git_tag"
    cd Common/
    ../gradlew build || exit 1
    cd ../NeoForge/
    ../gradlew build || exit 1
    cat ../build/libs/changelog.txt
    cd ../Fabric
    ../gradlew build || exit 1
    DO_RELEASE=true ../gradlew publishMods || exit 1
    cd ../NeoForge
    DO_RELEASE=true ../gradlew publishMods || exit 1
else
    echo "This is not a release version."
fi
