#!/bin/bash
# Ugly bug effective
cd Forge/
../gradlew build || exit 1
cat ../build/libs/changelog.txt
cd ../Fabric
../gradlew build || exit 1
DO_RELEASE=true ../gradlew publishMods || exit 1
cd ../Forge
DO_RELEASE=true ../gradlew publishMods || exit 1
