#!/bin/bash
# Ugly but effective
cd Common/
../gradlew build || exit 1
cd ../NeoForge/
../gradlew build || exit 1
cd ../Fabric
../gradlew build || exit 1
../gradlew publishMods || exit 1
cd ../NeoForge
../gradlew publishMods || exit 1
